const Blurb = {
	mother:
		'As a mother, you generally will spend more time caring for your child and are at increased risk of developing more severe trauma-related symptoms, like depression, anxiety, and somatization (physical symptoms related to distress)(1). You are also more likely to develop post-partum depression (2). Experiencing post-partum depression or increased stress is common and you should feel comfortable sharing any and all thoughts and feelings you have. Whether you talk to your loved ones, a therapist, or a support group, we encourage you to recognize you are not alone and taking care of yourself will improve your ability to care for your child. You both deserve you being in a better place.',
	motherolder1:
		'As a mother, you will generally spend more time caring for your child and are at increased risk of developing more severe trauma-related symptoms, like depression, anxiety, and somatization (physical symptoms related to distress).You are also more likely to develop post-partum depression (2). Experiencing post-partum depression or increased stress is common and you should feel comfortable sharing any and all thoughts and feelings you have. Whether you talk to your loved ones, a therapist, or a support group, we encourage you to recognize you are not alone and taking care of yourself will improve your ability to care for your child.',
	motherolder2:
		'It is also important to note, being an older parent increases your risk of experiencing suicidal thoughts or behaviors(1). Feeling stressed after life changing news is normal. Do not let any negative feelings keep you from reaching out to someone you trust. We recognize it sounds terrifying, suicidal thoughts and behaviors, and it is important to understand \' emotions sink at times and having dark thoughts is a natural part of the coping process. If you ever need someone to talk to call a loved one or 9-8-8 for a 24/7 lifeline staffed with certified crisis workers.',
	mothersevereicu:
		'As a mother of a baby with a severe CHD, you generally will spend more time caring for your child and are at increased risk of developing more severe trauma-related symptoms, like depression, anxiety, and somatization (physical symptoms related to distress)(1). You are also more likely to develop post-partum depression, especially if your baby has spent any time in the intensive care unit (2). Experiencing post-partum depression is common and you should feel comfortable sharing any and all thoughts and feelings you have. Whether you talk to your loved ones, a therapist, or a support group, we encourage you to recognize you are not alone and taking care of yourself will improve your ability to care for your child.',
	father:
		'As a father, you are at increased risk of developing trauma-related symptoms, like depression, anxiety, and somatization (physical symptoms related to distress) (1). Feeling stressed after life changing news is normal. Do not let any negative feelings keep you from reaching out to someone you trust.',
	fatherolder:
		'As a father, you are at increased risk of developing trauma-related symptoms, like depression, anxiety, and somatization (physical symptoms related to distress). Being an older parent increases your risk of experiencing suicidal thoughts or behaviors (1). Feeling stressed after life changing news is normal. Do not let any negative feelings keep you from reaching out to someone you trust. We recognize it sounds terrifying, suicidal thoughts and behaviors, and it is important to understand everyone emotions sink at times and having dark thoughts is a natural part of the coping process. If you ever need someone to talk to call a loved one or 9-8-8 for a 24/7 lifeline staffed with certified crisis workers.',
	siblingmodsevere:
		'As a sibling, you are likely to be impacted by the time your sibling will spend in medical settings and receiving care. This could affect family dynamics and cohesion. Know that your parents are trying, and you have a voice and should not hesitate to let them know how the changes you are or likely will see are affecting you.',
	family:
		'As a supporting family member, there is no concrete evidence showing an increased risk of developing trauma-related symptoms, however it is important to check-in with yourself periodically about how you are feeling regarding your loved one\'s condition. You are a valuable resource to your family, and should provide a supportive environment protecting your loved ones from isolating themselves. This will be a journey for you all.',
	employment:
		"The additional time needed to care for your loved one will likely have an impact on the household income, even employment and insurance status. Medical costs for your loved one's care can exceed $100k, with multiple out-of-pocket expenses greater than $1,000. (3) Visit our Resources page and/or talk with your provider regarding programs that may help alleviate some of the financial stresses of caring for your loved one.",
	parentlowses:
		'It is natural to find the time spent in the hospital and/or caring for your child overwhelming, and it is important to recognize and appreciate your own stress levels, as these may impact the relationship with your child and their overall development (4).',
	severeicu:
		"It is normal for part of your loved ones care to be spent in the intensive care unit. Understandably, this fact does not make the experience any easier and how you feel about your loved one's condition will almost certainly be tied to your perception of their health (4). You and your child's healthcare team is there to help you keep informed about the plan of care or your child's condition. ICUs are open 24/7 and there is always someone there to talk to if you have any questions. Do not hesitate to ask!",
	severeicusurgery:
		"Time in the intensive care unit usually follows surgical intervention on your child's heart defect, and is a normal part of your loved one\'s care.  Despite that, it is natural to have feelings of distress and concern for your little one's health (5). Understandably, this does not make the experience any easier and how you feel about your loved one's condition will almost certainly be tied to your perception of their health (4).  You and your child's healthcare team is there to help you keep informed about the plan of care or your child's condition. ICUs are open 24/7 and there is always someone there to talk to if you have any questions. Do not hesitate to ask!",
	breastfed:
		'As a breast-feeding parent, especially if you are having trouble, you are at increased risk of feeling detached from your baby, increasing your risk of becoming frustrated and having a lower self-esteem (6). If you are having difficulty, tell your pediatrician, primary care provider, or another member of your team, they are here to help you through the process.',
};

export default Blurb;
